import { auction1, auction2, auction3, auction4, auction5 } from "../assets";

export const liveAuctions1 = [
  {
    id: 1,
    img: auction1,
    heading: "Tristique diam a, enim, eros tellus. Viverra etiam",
    eth: "3.19 ETH",
    time: "22:41 min left",
    avatar,
    bid: "14 people are bidding",
    heart: true,
    heartNumber: 54,
  },
  {
    id: 2,
    img: auction2,
    heading: "Vulputate felis purus viverra morbi facilisi eget",
    eth: "2.55 ETH",
    time: "2:41 min left",
    avatar,
    bid: "35 people are bidding",
    heart: false,
    heartNumber: 120,
  },
  {
    id: 1,
    img: auction1,
    heading: "Tristique diam a, enim, eros tellus. Viverra etiam",
    eth: "2.55 ETH",
    time: "2:41 min left",
    avatar,
    bid: "14 people are bidding",
    heart: true,
    heartNumber: 54,
  },
  {
    id: 1,
    img: auction1,
    heading: "Tristique diam a, enim, eros tellus. Viverra etiam",
    eth: "2.55 ETH",
    time: "2:41 min left",
    avatar,
    bid: "14 people are bidding",
    heart: true,
    heartNumber: 54,
  },
  {
    id: 1,
    img: auction1,
    heading: "Tristique diam a, enim, eros tellus. Viverra etiam",
    eth: "2.55 ETH",
    time: "2:41 min left",
    avatar,
    bid: "14 people are bidding",
    heart: true,
    heartNumber: 54,
  },
];
