import {
  auction1,
  auction2,
  auction3,
  auction4,
  auction5,
  avatar1,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
} from "../assets";

export const liveAuctions1 = [
  {
    id: 1,
    img: auction1,
    heading: "Tristique diam a, enim, eros tellus. Viverra etiam",
    eth: 3.19,
    time: "22:41 min left",
    avatar: avatar1,
    bid: "14 people are bidding",
    heart: true,
    heartNumber: 54,
  },
  {
    id: 2,
    img: auction2,
    heading: "Vulputate felis purus viverra morbi facilisi eget",
    eth: 2.55,
    time: "2:41 min left",
    avatar: avatar2,
    bid: "35 people are bidding",
    heart: false,
    heartNumber: 120,
  },
  {
    id: 3,
    img: auction3,
    heading: "Dui accumsan leo vestibulum ornare eu",
    eth: 1.11,
    time: "22:59 min left",
    avatar: avatar3,
    bid: "101 people are bidding",
    heart: true,
    heartNumber: 570,
  },
  {
    id: 4,
    img: auction4,
    heading: "Senectus adipiscing nascetur accumsan etiam",
    eth: 1.63,
    time: "37:01 min left",
    avatar: avatar4,
    bid: "12 people are bidding",
    heart: true,
    heartNumber: 98,
  },
  {
    id: 5,
    img: auction5,
    heading: "Mattis at diam lorem nisl nam sed sociis",
    eth: 4.63,
    time: "12:15 min left",
    avatar: avatar5,
    bid: "12 people are bidding",
    heart: false,
    heartNumber: 98,
  },
];
